=== Amannroy/100DaysChallenge/XML(Day-23)/employee.xsd
<xs:schema xmlns:xs="http://www.example.com/2025/XML.Schema">
<xs:element name="employees">
    <xs:complexType>
       <xs:element name="employee">
          <xs:complexType>
             <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="age" type="xs:integer"/>
                <xs:element name="gender" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="phone" type="xs:string"/>
                <xs:element name="address" type="xs:string"/>
             </xs:sequence>
          </xs:complexType>
       </xs:element>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Amannroy/100DaysChallenge/XML(Day-23)/employee.xml
<employees xmlns="http://www.example.com/employee"
    xmlns:xsi="http://www.example.com/2025/XML.Schema-instance"
    xsi:schemaLocation="http://www.example.com/employee employee.xsd">
    <employee status="active">
        <name>Rahul</name>
        <age>26</age>
        <gender>Male</gender>
        <email>rahul@gmail.com</email>
        <phone>2345678945</phone>
        <address>61, North Campus, Hyderabad, India</address>
    </employee>

    <employee status="inactive">
        <name>Rohit</name>
        <age>32</age>
        <gender>Male</gender>
        <email>rohit@gmail.com</email>
        <phone>8765432167</phone>
        <address>123, Brigade Road, Bengaluru, India</address>
    </employee>
</employees>
